<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--<TargetFrameworks>net45;net46;netstandard2.0</TargetFrameworks>-->
    <TargetFramework>net6.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Company>opendocx</Company>
    <Product></Product>
    <Authors>opendocx, OpenXmlDev</Authors>
    <Description>The OpenDocx fork of Open-Xml-Power-Tools. Closely based on maintainer OpenXmlDev's vNext fork (as of April 2023), but includes only .NET 6.0 build target for use in cross-platform scenarios.

This version also includes a minor experimental extension that facilitates document composition, as well as a handful of bugfixes.</Description>
    <PackageProjectUrl>https://github.com/opendocx/Open-Xml-PowerTools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/opendocx/Open-Xml-PowerTools.git</RepositoryUrl>
    <AssemblyVersion>4.6.24.2</AssemblyVersion>
    <FileVersion>4.6.24.2</FileVersion>
    <Version>4.6.24-alpha2</Version>
    <PackageId>OpenXmlPowerTools-Net6</PackageId>
    <PackageLicenseUrl>https://opensource.org/licenses/MIT</PackageLicenseUrl>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.19.0" />
    <PackageReference Include="System.IO.Packaging" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="StyleCop.Analyzers" Version="1.1.118" />
  </ItemGroup>
</Project>